package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/mux"

	_ "github.com/nakonechniyd/money_wizard/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"

	apiv1 "github.com/nakonechniyd/money_wizard/api/v1"
)

// @title Money Wizard API
// @version 1.0
// @description Simple calculation of human wealth accumulation
// @BasePath /
func main() {

	host := flag.String(
		"h", "localhost", "Service host address",
	)
	port := flag.String(
		"p", "8080", "Service port",
	)
	flag.Parse()

	router := mux.NewRouter().StrictSlash(true)

	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)

	apiv1.AddRouts(router)

	srv := &http.Server{
		Addr:         fmt.Sprintf("%s:%s", *host, *port),
		Handler:      router,
		WriteTimeout: 1 * time.Second,
		ReadTimeout:  1 * time.Second,
	}

	fmt.Printf("Running on http://%s:%s\n", *host, *port)
	log.Fatal(srv.ListenAndServe())
}
